CarWash/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('userview.urls')),
    path('home/',include('home.urls')),
    path('order/',include('order.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)



#+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .import views 


urlpatterns = [
    path('packages/',views.packages,name='packages'),
    path('booking/<int:book_id>/', views.booking, name='booking'),
    
    path('dashboard/',views.dashboard, name='dashboard'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    path('change_password/',views.change_password,name='change_password'),
    path('myorders/',views.myorders, name="myorders"),
    path('order_detail/<int:order_id>/',views.order_detail, name="order_detail"),
    path('cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),
]

home/models.py
from django.db import models
from userview.models import CustomUser
from django.contrib.auth.models import Group
# Create your models here.


class VehicleCategory(models.Model):
    name = models.CharField(max_length=100, null=True)
    
    def __str__(self):
        return self.name

class Package(models.Model):    
    category = models.ForeignKey(VehicleCategory,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='packages/', null=True, blank=True) 
    name = models.CharField(max_length=100, null=True,)
    description = models.TextField(null=True)
    
    def __str__(self):
        return self.name
    
class Vehicletype(models.Model) :
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class Variations(models.Model):
    package = models.ForeignKey(Package,on_delete=models.CASCADE)
    vehicle_type = models.ForeignKey(Vehicletype,on_delete=models.CASCADE)
    price = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.package


class Slot(models.Model):
    date = models.DateField(null=True, blank=True)
    available_slots = models.CharField(max_length=100)
    is_locked = models.BooleanField(default=False)
    groups = models.ManyToManyField(Group)

    def __str__(self):
        return self.available_slots

class SlotBooking(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    slot = models.ForeignKey(Slot, on_delete=models.CASCADE)
    booking_date = models.DateField(null=False)
    is_booked = models.BooleanField(default=False)
    
    
    def __str__(self):
        return f"{self.slot} - {self.booking_date}"


class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    package = models.ForeignKey(Package,on_delete=models.CASCADE,default=None,null=True)
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    vehicle_no = models.CharField(max_length=50)
    variation = models.ForeignKey(Variations, on_delete=models.CASCADE, null=True,blank=True)
    slot_booking = models.ForeignKey(SlotBooking, on_delete=models.CASCADE)
    is_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # def __init__(self,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
        
    #     for field in self.fields :
    #         self.fields[field].widget.attrs['class'] = 'form-control'

class Userprofile(models.Model):
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    address_line = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    
    def fullname(self):
        return f"{self.user.first_name} {self.user.last_name}"
    
    
    
    
  

home/forms.py
from datetime import datetime,timedelta
from django import forms
from .models import *
from userview.models import CustomUser

class DateInput(forms.DateInput):
    input_type = 'date'    



# class CarwashForm(forms.ModelForm):
#     class Meta:
#         model=CarWashPackage
#         fields = ('image', 'name', 'description','vehicle_type','price')
        
class BookingForm(forms.ModelForm):
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'date',
            'min': (datetime.now().date() + timedelta(days=1)).strftime('%Y-%m-%d'),  # Set the minimum date to tomorrow
            'max': (datetime.now().date() + timedelta(days=5)).strftime('%Y-%m-%d'),  # Set the maximum date to five days later
        })
    )
    class Meta :
        model = Booking
        fields = ('make','model','vehicle_no','start_date')
                
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['start_date'].required = False
        

class UserForm(forms.ModelForm):
    
    class Meta : 
        model = CustomUser
        fields = ('first_name','last_name','phone','email')
        
    def __init__(self, *args, **kwargs):
        super(UserForm,self).__init__(*args, **kwargs) 
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
    
class UserProfileForm(forms.ModelForm):
    
    class Meta : 
        model = Userprofile
        fields = ('address_line','city','state','country')
        
    def __init__(self, *args, **kwargs):
        super(UserProfileForm,self).__init__(*args, **kwargs) 
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    

home/views.py
from datetime import datetime, timedelta, timezone
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
import razorpay
from django.utils import timezone
from CarWash import settings
from .forms import *
from .models import *
from django.contrib.auth.models import Group
from django.shortcuts import get_object_or_404
from django.contrib import messages
from order.forms import *
from userview.views import delete_booking
from django.db.models import Count


@login_required
def dashboard(request) :
    user = request.user
    orders = OrderProduct.objects.order_by('-created_at').filter(user=user,order__is_canceled=False)
    order_count = orders.count()
    context = { 
        'order_count':order_count,
        'user': user
    }
    return render(request,'home/dashboard.html',context)

      

def packages(request):
    print(request,"sdfghjkl")
    packages = Package.objects.all()
    delete_booking(request)
    try:
        price = 0
        value = request.POST.get('category')
          
        if value == 'car':
            packages = Package.objects.filter(category__name='CAR')
            return render(request, 'home/packages.html', {'packages': packages, 'price': price})
        elif value == 'bike':
            packages = Package.objects.filter(category__name='BIKE')
            return render(request, 'home/packages.html', {'packages': packages, 'price': price})
        else :
            pass
    except Exception as e:
        pass
    context = {
    'packages': packages, 
    'price': price,
    # 'variation':variation
    }
    return render(request, 'home/packages.html', context)




    
def booking(request, book_id):
    booked_slots = SlotBooking.objects.all().values('slot__available_slots','booking_date')
    print('booked_slots: ',booked_slots)
    user = request.user
    package = Package.objects.get(id=book_id)
    price=0
    morning_slot = Slot.objects.filter(groups__name='morning')
    afternoon_slot = Slot.objects.filter(groups__name='afternoon')
    evening_slot = Slot.objects.filter(groups__name='evening')
    
    current_date = datetime.now().date()
    
    five_days_later = current_date + timedelta(days=4)
    date_list = []
    while current_date <= five_days_later:
        date_list.append(current_date)
        current_date += timedelta(days=1)
    if request.method == 'POST':
        print(request.POST)
        form = BookingForm(request.POST)
        if form.is_valid():
            selected_date = request.POST.get('selected_date')
            selected_slot_id = request.POST.get('selected_slot')
            slot_instance = get_object_or_404(Slot, pk=selected_slot_id)
            price=request.POST.get('price')
            
            slot_booking, created = SlotBooking.objects.get_or_create(
                user=request.user,
                slot=slot_instance,
                booking_date=selected_date
            )
            slot_booking.save()
            print(slot_booking)
            
            if not slot_booking.is_booked:
                # Proceed with booking
                booking = Booking.objects.create(
                    user=slot_booking.user,  # Associate the booking with the logged-in user
                    make=form.cleaned_data['make'],
                    model=form.cleaned_data['model'],
                    vehicle_no=form.cleaned_data['vehicle_no'],
                    slot_booking=slot_booking,
                    package = package       
                )
                # Mark the slot as booked
                slot_booking.is_booked = True
                slot_booking.save()
                context= {
                        'order':Booking.objects.get(id = booking.id,),
                        'form' : OrderForm(),
                        'packages':Package.objects.get(pk=package.id),
                        'price':price,
                }
                return render(request, 'order/place_order.html',context)
                
            else:
                # The slot is already booked for the selected date
                form.add_error('start_date', 'The selected slot is not available for booking.')
        else:
            # Handle the case when the selected_date is None or empty
            form.add_error('start_date', 'Please select a valid date.')
    
    else:
        form = BookingForm()
        form.fields['start_date'].widget.attrs['min'] = current_date
        form.fields['start_date'].widget.attrs['max'] = five_days_later
        price=request.GET.get('price')
        

    context = {
        'booked_slots':booked_slots,
        'package': package,
        'user': request.user,
        'form': form,
        'morning_slot': morning_slot,
        'afternoon_slot': afternoon_slot,
        'evening_slot': evening_slot,
        'date_list': date_list,
        'price':price,
    }
    return render(request, 'home/booking.html',context)



@login_required(login_url='login')
def myorders(request) :
    orders = OrderDetails.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    context ={
        'orders':orders
    }
    return render(request,'home/myorders.html',context)



def order_detail(request,order_id):
    print(order_id)
    order_detail = OrderProduct.objects.get(order__order_number=order_id)
    order = OrderDetails.objects.get(order_number=order_id)
   
    context = {
        'order_detail':order_detail,
        'order':order,
    }
    return render(request,'home/order_detail.html',context)


def cancel_order(request, order_id):
    print(order_id)
    order = get_object_or_404(OrderDetails, id=order_id)
    
    # booking_time = order.slot_booking.slot
    # print(booking_time)
    # current_time = datetime.now()
    # print(current_time)
    # time_difference = booking_time - current_time
    # print(time_difference)
    
    if request.method == 'POST':
        order.is_canceled = True
        order.save()
        c = SlotBooking.objects.get(id=order.slot_booking.id)
        c.is_booked = False
        c.save()
        messages.success(request, 'Your Order is Cancelled Successfully')
    
    
        return redirect('myorders')
        
    context = {
        'order': order,
    }
    return render(request, 'home/myorders.html', context)


        
        # client = razorpay.Client(auth =(settings.RAZOR_PAY_KEY_ID, settings.KEY_SECRET))
        
        # payment_id = order.payment_id
        # print(payment_id)
        # refund_amount = order.payment.amount_paid
        # print(refund_amount)
        
        # refund_data = {
        #     "amount": refund_amount * 100,  # Razorpay expects amount in paise
        #     "speed": "normal",  # Or "immediate" for instant refund
        #     "receipt": f"refund_{payment_id}",  # Unique receipt for the refund
        #     "note": "Refund for canceled order",
        #     # You might need additional fields like UPI ID to process the refund
        # }
        # try:
        #     refund = client.payment.refund(payment_id, refund_data)
        #     # Process the refund response and update your database if needed
        #     refund_status = refund.get('status')  # Check if the refund was successful
        #     if refund_status == 'processed':
        #         # Update your order or refund status accordingly
        #         order.refund_status = 'processed'
        #         order.save()
        #         messages.success(request, 'Refund processed successfully')
        #     else:
        #         messages.error(request, 'Refund processing failed')
        # except RazorpayError as e:
        #     messages.error(request, 'An error occurred during refund processing')

        # order.slot_booking.is_booked=False
        
    
    



@login_required(login_url='login')
def edit_profile(request):
    userprofile, created = Userprofile.objects.get_or_create(user=request.user)

    if request.method == 'POST' :
        user_form = UserForm(request.POST, instance = request.user)
        user_profile = UserProfileForm(request.POST, instance = userprofile)
        if user_form.is_valid() and user_profile.is_valid():
            user_form.save()
            user_profile.save()
            messages.success(request, 'Your Profile has been Updated') 
            return redirect('edit_profile')
    else :
        user_form = UserForm(instance=request.user)
        user_profile = UserProfileForm(instance=userprofile)
        
    context = {
        'user_form':user_form,
        'user_profile':user_profile
    }
    return render(request, 'home/edit_profile.html',context)



@login_required(login_url='login')
def change_password(request):
    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        
        user = CustomUser.objects.get(username__exact= request.user.username)
        
        if new_password == confirm_password :
            success = user.check_password(current_password)
            if success :
                user.set_password(new_password)
                user.save()
                # auth.logout(request)
                messages.success(request,'Password updated Successfully')
                return redirect('change_password')
            else :
                messages.error(request,'Enter Valid Current Password')
                return redirect('change_password')
        else :
            messages.error(request,'Password does not match')
            return redirect('change_password')
    return render(request, 'home/change_password.html')



    

templates/home/booking.html
{% extends 'base.html' %}


{% block content %}
{% include 'includes/navbar.html' %}

<style>
  /* Styling for date boxes */
  .date-box {
    border: 1px solid #ccc;
    padding: 10px;
    margin: 5px;
    width: 100%;
    text-align: center;
    cursor: pointer;
  }
  a{
    text-decoration:None;
    color:black;
  }

  .date-box.checked {
    background-color: red;
    color: white;
  }

  /* Styling when date box is clicked */
  .date-box.active {
    background-color: #007bff;
    color: #fff;
  }

  /* Additional styles to improve appearance */
  .date-box label {
    display: block;
    text-align: center;
    font-weight: bold;
  }

  /* Clear floats for row */
  .row::after {
    content: "";
    clear: both;
    display: table;
  }
  .slot-box {
    border: 1px solid #ccc;
    padding: 10px;
    margin: 5px;
    width: 350px;
    text-align: center;
    display: inline-block;
  }
    .change-link {
      position: absolute;
      top: 10px;
      right: 10px;
      color: #007bff;
      font-weight: bold;
      text-decoration: none;
    }
    .content {
      padding-top:100px;
    }
    .slot-box.booked {
      background-color: red;
    }
</style>
<!-- booking_form.html -->

<h1 class="text-center mt-3 ">Booking</h1>

<section class="section-content padding-y bg content">
<article class="card mb-4">
  <div class="card-body">
    <h4 class="card-title mb-4">Review cart</h4>
    <div class="row">
      <div class="col-md-6">
        <figure class="itemside mb-4">
            <p>Package: {{package.name}}</p>
            <p>Price: {{ price }}</p>
          </figure>
        </div> <!-- col.// -->
      </div> <!-- row.// -->
      <a href="{% url 'packages'  %}" class="change-link">Change</a>
    </div> <!-- card-body.// -->
  </article>

<div class="container">
  <div class="row">
    <div class="col-md-10">
      <div class="card">
        <!-- Card header -->
        <div class="card-header text-center">
          Booking
        </div>
        <!-- Card body -->
      <div class="card-body">
        <form method="post"   >
          {% csrf_token %}
          <div>
              <h3>Car Details :</h3>
          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                  <label for="make">Make:</label>
                  {{form.make}}
                </div>
              </div>
              
              <!-- Column 2 -->
              <div class="col-md-4">
                <div class="form-group">
                  <label for="model">Model:</label>
                  {{form.model}}
                </div>
              </div>
            </div>
              <div class="row">

                <!-- Column 3 -->
                <div class="col-md-4">
                <div class="form-group">
                  <label for="registration_no">Vehicle No:</label>
                   {{form.vehicle_no}}
                </div>
              </div>
            </div>

            <div class="mb-3">
              <input type="hidden" id="selected_date" name="selected_date" value="" required>
              <h3>Select Date and Time of Service :</h3>
              <div class="container">
                <div class="row mt-3">
                  {% for date_choice in date_list %}
                    <div class="col-md-2">
                      <div id="{{ date_choice }}" onClick="handleDate('{{ date_choice }}')" class="date-box form-group" data-date="{{ date_choice }}"
                      style="{% if date_choice in booked_slots %}background-color: red;{% endif %}">
                        <label>{{ date_choice|date:"D d" }}</label>
                      </div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>

            <div class="col-md-12 mt-3">
            <input type="hidden" id="selected_slot" name="selected_slot" value="" required>
              <h4 class="mb-3">Pick Time Slot <small>(14 Slots Available)</small></h4>
              <div class="form-group" id="time" >
                <h3 class="mt-3">Early Morning Slot</h3>
                {% for s in morning_slot %}
                <div onclick="handleTime({{ s.pk }})" id="{{ s.pk }}" class="slot-box {% if s.is_booked %}booked{% endif %}">
                  {{ s.available_slots }} 
                </div>
                  
                {% endfor %}
                
                
                <h3 class="mt-3">Afternoon Slot</h3>
                {% for s in afternoon_slot %}
                <div onclick="handleTime({{ s.pk }})" id="{{ s.pk }}" class="slot-box {% if s.is_booked %}booked{% endif %}" > 
                  {{ s.available_slots }}
                </div>
       
                {% endfor %}
                
                <h3 class="mt-3" >Evening Slot</h3>
                {% for s in evening_slot %}
                <div onclick="handleTime({{ s.pk }})" id="{{ s.pk }}" class="slot-box {% if s.is_booked %}booked{% endif %}" >
                  {{ s.available_slots }}
                </div>
                </a>
                  {% endfor %}  
               
                </div>
              </div>
          </div> 
        </div>
            
            <input type='hidden' name='price' value='{{ price }}' />
            <button type="submit" class="btn btn-dark">Continue</button>

        </form>
          <!-- You can add more content here -->
        </div>
      </div>
    </div>
  </div>
</div> 

<script>

  function handleDate(date) {
    var elements = document.getElementsByClassName('date-box form-group');
    var price = parseFloat("{{ price }}");

    for (var i = 0; i < elements.length; i++) {
      elements[i].style.backgroundColor = 'white';
    }
  
    var myDiv = document.getElementById(date);
    myDiv.style.backgroundColor = 'blue';
  
    const dateObj = new Date(date);

    const year = dateObj.getFullYear();
    const month = String(dateObj.getMonth() + 1).padStart(2, '0');
    const day = String(dateObj.getDate()).padStart(2, '0');

    // Construct the formatted date string in YYYY-MM-DD format
    const formattedDate = `${year}-${month}-${day}`;

    // Set the formatted date to the selected_date field
    document.getElementById('selected_date').value = formattedDate;
    console.log(formattedDate);  }
  

  function handleTime(slotId){
    
    var elements = document.getElementsByClassName('slot-box');
    
    for (var i = 0; i < elements.length; i++) {
      elements[i].style.backgroundColor = 'white';
    }

    var myDiv = document.getElementById(slotId)

    var hi = myDiv.innerHTML;
    
    myDiv.style.backgroundColor = 'blue';
  
    document.getElementById('selected_slot').value = slotId; // Set the slotId directly
    console.log(slotId)
  }
  
</script>


{% endblock content %}

templates/home/change_password.html
{% extends 'base.html' %}

{% block content %}

{% include 'includes/navbar.html' %}

<section class="section-conten padding-y bg mt-5">

{% comment %} {% include 'includes/alerts.html' %} {% endcomment %}

    <div class="container">
        <div class="row">
        {% include 'includes/sidebar.html' %}
        <main class="col-md-9">
            {% include 'includes/alerts.html' %}
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Change Password</strong>

            </header>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                      <form action="" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                          <div class="form-group col-md-12">
                            <label>Current Password</label>
                            <input type="password" class="form-control" name="current_password" placeholder='Current Password' required>
                          </div>
                          <div class="form-group col-md-12">
                            <label>New Password</label>
                            <input type="password" class="form-control" name="new_password" placeholder='New Password' required>
                          </div>
                          <div class="form-group col-md-12">
                            <label>Confirm Password</label>
                            <input type="password" class="form-control" name="confirm_password" placeholder='Confirm Password' required>
                          </div>
                          
                          <input type="submit" value="Save" class="btn btn-dark" style='width:100%'>
                      </form>
                    </div>


                </div>
            </div>

            </article>
        </main>
    </div>
    </div>

    </section>
{% endblock %}

templates/home/packages.html
{% extends 'base.html' %}
{% load static %} 

{% block content %} 


{% include 'includes/navbar.html'%}

<style>
  .package-image {
    padding-right: 0;
  }

  .img {
    max-width: 30%;
    max-height: 30%;
  }

  .package-item {
    display: flex;
    align-items: flex-start; /* Adjust alignment */
    margin-bottom: 20px; /* Adjust the vertical gap between items */
  }
  {% comment %} .add-to-cart-btn {
    position: absolute;
    bottom: 5px;
    right: 5px;
  } {% endcomment %}

  .package-details {
    display: flex;
    justify-content: space-between;
    margin-top: 20px;
  }
  .price-wrap {
    font-size: 18px;
    font-weight: bold;
  }
  .package-column {
    flex: 0 0 50%;
    padding: 10px;
    margin-bottom: 10px;
  }

  .package-info {
    display: flex;
    align-items: flex-start;
    margin-left: 10px; /* Adjust the gap between image and text */
  }

  /* Add this style to align radio buttons with the package details */
  .package-radio {
    display: flex;
    align-items: center;
  }

  .package-radio label {
    margin-right: 10px;
  }
  .button-row {
    display: flex;
    justify-content: center; /* Horizontally center the buttons */
    align-items: center; /* Vertically center the buttons */
  }

  .button-row button {
    /* Add any additional styles for the buttons if needed */
    margin: 5px;
  }
  .card {
    position: relative;
    display: flex;
    flex-direction: column;
  }
  .card .card-body {
    flex: 1;
  }
  .card .add-to-cart-btn {
    margin-top: auto;
    align-self: flex-end;
    margin-top:170px
  }
</style>

<h1 class="text-center mt-3" style="color:#fff">Scheduled Packages</h1>
<form method="post" action="">
  {% csrf_token %}
<div class="button-row mt-3">
  <button 
  type="submit"
  name="category"
  value="car"
  class="btn btn-lg btn-primary"
  >
  <i class="fa-solid fa-car-side"></i>
  CAR
</button>
<button
type="submit"
name="category"
value="bike"
class="btn btn-lg btn-primary"
>
<i class="fa-sharp fa-solid fa-motorcycle"></i>
BIKE
</button>
</div>
</form>

<div class="row mt-4">
  <aside class="col-lg-9 mx-auto">
    <div class="card">
      <table class="table table-borderless table-shopping-cart">
        <thead class="text-muted">
          <tr class="small text-uppercase">
            <th scope="col">Product</th>
            <th scope="col" class="text-right">Vehicle Type</th>
            <th scope="col" class="text-right">Price</th>
            <th scope="col" class="text-right"></th>
          </tr>
        </thead>
        <tbody>
          {% for package in packages %}
          <form method="GET" action="{% url 'booking' package.id  %}">
            
            <tr>
              <td>
                <div class="d-flex align-items-start package-info">
                  <img
                  class="img img-sm"
                    src="{% static 'packages/'|add:package.image %}"
                    alt="{{ package.name }}"
                  />
                  <div class="card-body">
                    <!-- Package Details -->
                    <h4 class="">{{ package.name }}</h4>
                    <div class="package-details">
                      <div class="package-column">
                        <ul>
                          <li>Exterior Wash</li>
                          <li>Interior Vacuuming</li>
                          <li>Tire and Wheel Cleaning</li>
                          <li>Interior Wiping and Dusting</li>
                        </ul>
                      </div>
                      <div class="package-column">
                        <ul>
                          <li>Glass and Mirror Cleaning</li>
                          <li>Fragrance</li>
                          <li>Air Filter Cleaning</li>
                          <li>Spectrum</li>
                        </ul>
                      </div>
                    </div>
                    <!-- End Package Details -->
                  </div>
                </div>
              </td>

              <td class="package-radio">
                <!-- Use the package-radio class to align the radio buttons -->
                <div class="row" style="margin: 0">
                  <!-- Add inline style to remove margin -->
                  <div class="item-option-select">
                    <h6>Choose Type</h6>
                    <option value="" disabled selected>Choose</option>
                    <select name="vehicle_type" onchange="handleChange(this,'{{ package.id }}')">
                      {% for i in package.variations_set.all %}
                      <option value="{{ i.vehicle_type | lower }}" data-id="{{ i.price }}">
                        {{ i.vehicle_type | capfirst }} 
                      </option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <!-- row.// -->
              </td>
              <td class="package-price">
                <h6>Price: <span class="span-{{package.id}}">0</span></h6>
              </td>
              <td class="text-right">
                <div class="add-to-cart-btn">
                  <input type="hidden" name="price" class="input-{{package.id}}" value="" >

                  
                  <button type="submit" class="btn btn-success">Book Now</button>
                </div>
              </td>
            </tr>
            
          </form>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- card.// -->
    </aside>
    <!-- col.// -->
  </div>
  <!-- row.// -->

<script>
  {% comment %} var initialPrice = document.getElementById("{{ package.id }}").textContent; {% endcomment %}
  const price = {{price}};

  function handleChange(selectElement, id) {
    var selectedOption = selectElement.options[selectElement.selectedIndex];
    var selectedId = selectedOption.getAttribute("data-id");

    var myDiv = document.getElementsByClassName("span-"+id)
    for (var i = 0; i < myDiv.length; i++) {

      var myDiv = myDiv[i];
      myDiv.innerHTML = selectedId;
  }


  var myInput = document.querySelector(".input-" +id);

if (myInput) {
    myInput.value = selectedId;
}

    price = selectedId;
  

  }
  
 
</script>

{% endblock content %}